# Generated by Django 3.0.2 on 2020-01-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boot_rules', '0002_auto_20200106_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='elements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='scss',
            field=models.TextField(default=''),
        ),
    ]
