# Generated by Django 3.0.2 on 2020-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boot_rules', '0003_auto_20200107_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='elements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='scss',
            field=models.TextField(blank=True, default=''),
        ),
    ]
